import * as readline from 'readline';
import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';
import { randomUUID } from 'node:crypto';
import type { ConfigEditKey } from '@shared/config-ack';
import { createClaudeBackend } from './providers/claude';
import { createCodexBackend } from './providers/codex';
// `copilot` is driven by the ACP backend (the native SDK backend was deleted at
// cutover — recoverable from git history at the pre-cutover commit).
import { createCopilotBackend } from './providers/copilot';
import { createFakeBackend } from './providers/fake';
import { deleteContext, cleanupOldContexts } from './context-store';
import { runCleanupSweep } from './cleanup';
import { performShutdown } from './shutdown';
import { SESSION_ENV_KEY, writeLease, removeLease as removeSessionLease, sweepDeadSessions } from './session-sweep';
import { findPidsByEnv, readProcStartTime } from './proc-scan';
import { loadRestoreContextFor, newExecutionId, wrapSendForContext, wrapSendForExecution } from './orchestrator';
import { initAppToolClient, resolveAppToolResult } from './app-tool-client';
import { setLogSink, serverLog } from './server-logger';
import { setWireSink } from './logger';
import { createSendQueue } from './send-queue';
import { createBackendRegistry, type BackendFactory } from './backend-registry';
import { projectAppSkills } from './providers/shared';
import type { AgentAttachment, AgentPrefs } from '@shared/types';
import type { OutgoingMessage, QueryInput, ServerBackend, PickerResolvePayload, ModelCacheClient } from './providers/types';
import type { ProviderModel, AgentProvider } from '@shared/types';
import {
  CLAUDE_PROVIDER,
  CODEX_PROVIDER,
  COPILOT_PROVIDER,
  FAKE_PROVIDER,
} from '@shared/agent-providers';
import { MEMORY_WIRE_TYPE } from '@shared/process-memory';
import { sampleMemoryUsage, scheduleInitialMemoryReport } from './memory-report';

// Reuse the shared registry-derived union — no separate list to keep in sync.
type Provider = AgentProvider;

interface IncomingMessage {
  type: 'send' | 'stop' | 'cancel_queued' | 'ping' | 'resolve_permission' | 'resolve_picker' | 'get_capabilities' | 'store_credential' | 'clear_credential' | 'clear_context' | 'read_task_output' | 'stop_task' | 'reload_skills' | 'app_tool_result' | 'cache_reply' | 'start_login' | 'cancel_login' | 'reconnect' | typeof MEMORY_WIRE_TYPE.GET_USAGE;
  provider?: Provider;
  /**
   * For `type: 'send'`: executionId generated by main side so it can pre-register
   * the per-execution event dispatcher before we start emitting. Missing executionId
   * falls back to a freshly-generated one — defensive only; main always sets
   * it in the current architecture.
   */
  executionId?: string;
  prompt?: string;
  cwd?: string;
  resume?: string;
  permissionMode?: string;
  model?: string;
  effort?: string;
  images?: string[];
  attachments?: AgentAttachment[];
  sessionId?: string;
  /**
   * App/tab SESSION routing key (dispatch-layering) — the demux dimension for
   * the out-of-execution messages (`resolve_permission`/`resolve_picker`/`stop_task`)
   * that today route via `activeBackend` ("whoever sent last"). DISTINCT from
   * `sessionId` (the context-store / SDK key). Populated by main now; consumed
   * once the harness routes by sid (group C). Forward-compat seam until then.
   */
  sid?: string;
  /** For `type: 'send'`: a structured config edit (picker / status-bar). When
   *  present, the provider applies it + emits a divider instead of running a
   *  query — prompt is empty for these executions. */
  configEdit?: { key: ConfigEditKey; value: string };
  /** For `type: 'send'` / `type: 'cancel_queued'`: renderer-minted correlation
   *  key. Tracked through the send queue + echoed in the queue snapshot. */
  clientMsgId?: string;
  toolUseId?: string;
  allow?: boolean;
  /** For `type: 'ping'`: client heartbeat sequence, echoed back in pong for RTT. */
  seq?: number;
  /** For `type: 'send'` AND `type: 'get_capabilities'`: app-instance id — names
   *  this app's projected skills dir at `~/.shelf/apps/<appId>/skills` (see
   *  deployment#1). Carried on caps too so config-home providers (copilot --acp)
   *  can set COPILOT_HOME at the caps-time CLI spawn. */
  appId?: string;
  /** resolve_picker payload — picker id minted by provider, payload carries
   * index-aligned answers or { cancelled: true } (see PickerResolvePayload). */
  pickerId?: string;
  payload?: PickerResolvePayload;
  message?: string;
  requestId?: string;
  /** For `type: 'app_tool_result'`: main's reply to an app_tool request. */
  ok?: boolean;
  data?: unknown;
  error?: string;
  key?: string;
  customModels?: ProviderModel[];
  scope?: 'once' | 'session';
  /** For `type: 'read_task_output'`: which background task's remote output_file to read. */
  taskId?: string;
  /**
   * For `type: 'get_capabilities'`: renderer's saved prefs forwarded so
   * session-stateful providers (Copilot) can seed currentModel/currentEffort/
   * currentPermissionMode closures before reporting `current*` back.
   */
  intent?: AgentPrefs;
}

// Session id assigned by the dispatcher at spawn (`--sid=<sid>`); undefined when
// main spawns this exec proc directly (pre-dispatcher / today's path). See send().
const EXEC_SID = process.argv.find((a) => a.startsWith('--sid='))?.split('=')[1];

function send(msg: OutgoingMessage) {
  // Under the dispatcher (dispatch-layering, option B), the exec proc stamps its
  // own `sid` on EVERY outbound message so the dispatcher can relay exec→main RAW
  // — opaque line-forwarding, never parsing the hot token stream — and main demuxes
  // by sid. Spawned directly by main (no --sid), this is a no-op → today's wire.
  const stamped = EXEC_SID ? ({ ...msg, sid: EXEC_SID } as OutgoingMessage) : msg;
  // Wire-TX diagnostic trace (debug level → off by default; flip logLevel=debug
  // to capture). Proves which events the provider actually emitted over stdout —
  // the top of the chain when tracing a sleep/network wedge where tool results
  // never reach the renderer. Skip `type:'log'` to avoid recursion (serverLog
  // routes back through this same send) and log spam. See connection-wedge trace.
  const m = stamped as unknown as Record<string, unknown>;
  if (m.type !== 'log') {
    serverLog('debug', 'wire-tx', wireSummary(m));
  }
  process.stdout.write(JSON.stringify(stamped) + '\n');
}

// ── Model-cache client (dispatch-layering group E) ───────────────────────────
// Only under a dispatcher (EXEC_SID set) is there a per-host cache servicing
// cache_get on its side-channel. Without one, get resolves a MISS → the provider
// fetches as today. `cache_reply` (dispatcher→exec) resolves the pending get.
const pendingCacheGets = new Map<string, (r: { hit: boolean; value?: unknown }) => void>();
let cacheReqSeq = 0;
function resolveCacheReply(requestId: string, hit: boolean, value: unknown): void {
  const r = pendingCacheGets.get(requestId);
  if (r) { pendingCacheGets.delete(requestId); r({ hit, value }); }
}
const modelCacheClient: ModelCacheClient | undefined = EXEC_SID ? {
  get: (key, provider) => new Promise((resolve) => {
    const requestId = `cg-${cacheReqSeq++}`;
    pendingCacheGets.set(requestId, resolve);
    send({ type: 'cache_get', requestId, key, provider } as unknown as OutgoingMessage);
    // Safety net: a slow/absent dispatcher must not hang init → resolve a miss.
    // A timeout is a real anomaly (the dispatcher should always reply) → fail-loud.
    setTimeout(() => {
      if (pendingCacheGets.delete(requestId)) {
        serverLog('warn', 'cache', `cache_get ${key}:${provider} timed out (no dispatcher reply in 2s) — treating as miss`);
        resolve({ hit: false });
      }
    }, 2000).unref?.();
  }),
  put: (key, provider, value) => { send({ type: 'cache_put', key, provider, value } as unknown as OutgoingMessage); },
} : undefined;

/** Compact one-line summary of a wire message for the wire-tx/wire-rx traces. */
function wireSummary(m: Record<string, unknown>): string {
  const bit = (k: string, v: unknown) => (v == null ? '' : ` ${k}=${String(v).slice(0, 12)}`);
  return `type=${String(m.type)}${bit('execution', m.executionId)}${bit('msgType', m.msgType)}${bit('msgId', m.msgId)}`
    + (typeof m.content === 'string' ? ` len=${m.content.length}` : '');
}

// Route all agent-server diagnostics back to main over the wire (see
// server-logger.ts). After this, serverLog() no longer falls back to stderr.
setLogSink(send);
// New logger facade (wireLogger) shares the same wire writer. `channel` rides as
// an extra JSON field; send() forwards it verbatim. Cast bridges the decoupled
// WireLogMessage to OutgoingMessage (its {type:'log'} variant) at this one seam.
setWireSink((m) => send(m as unknown as OutgoingMessage));

// Last appId seen on a `send` — names this app's projected skills dir; used to
// keep its `.heartbeat` lease fresh + protect it from the startup sweep.
let lastAppId: string | undefined;

/**
 * Refresh the `.heartbeat` leases the cleanup sweep reads (see #70 / §5.9):
 * the version dir (when running under `~/.shelf/agent-server/<version>/`; local
 * dist runs skip it) and this app's `~/.shelf/apps/<appId>/` dir. Best-effort —
 * never break the pong reply.
 */
function touchHeartbeats(): void {
  try {
    if (/\.shelf\/agent-server\//.test(__dirname)) {
      fs.writeFileSync(path.join(__dirname, '.heartbeat'), '');
    }
  } catch { /* version lease best-effort */ }
  try {
    if (lastAppId) {
      const appDir = path.join(os.homedir(), '.shelf', 'apps', lastAppId);
      fs.mkdirSync(appDir, { recursive: true });
      fs.writeFileSync(path.join(appDir, '.heartbeat'), '');
    }
  } catch { /* app lease best-effort */ }
}

// Phase-2 crash net: tag THIS agent-server's process env so every provider CLI +
// detached task it spawns inherits SHELF_SESSION=<uuid> (set before any CLI spawns
// — spawns happen on message handling, well after boot). If we ever die abnormally
// (hard crash / force-kill, skipping the normal-closure reap), the NEXT launch's
// startup sweep finds still-alive tagged orphans and kills them. See session-sweep.ts.
const SHELF_SESSION = randomUUID();
process.env[SESSION_ENV_KEY] = SHELF_SESSION;

async function reportMemoryUsage(): Promise<void> {
  try {
    const supplementaryPids = process.platform === 'linux'
      ? findPidsByEnv(SESSION_ENV_KEY, SHELF_SESSION)
      : [];
    send(await sampleMemoryUsage({ kind: 'exec', supplementaryPids }));
  } catch (error) {
    serverLog('error', 'memory', `exec memory report failed: ${error instanceof Error ? error.message : String(error)}`);
  }
}

scheduleInitialMemoryReport(reportMemoryUsage);

let activeBackend: ServerBackend | null = null;

/**
 * Per-session pref cache. Orchestrator drives "did renderer change pref X
 * since last send?" diff detection — calls backend.setModel/setEffort/
 * setPermissionMode only on change. Keyed by sessionId so multi-tab
 * scenarios don't cross-contaminate each other's diff state (which the
 * old per-provider-singleton closure cache in Copilot did suffer from).
 */
const lastAppliedPrefs = new Map<string, { model?: string; effort?: string; permissionMode?: string }>();

async function applyPrefDiff(
  backend: ServerBackend,
  sessionKey: string,
  incoming: { model?: string; effort?: string; permissionMode?: string },
): Promise<void> {
  // Cache update is gated on apply success — a failed setX must not record
  // the requested value as "applied" or the next execution's diff would skip the
  // retry (silently leaving the SDK on the prior value while the cache
  // pretends the switch happened).
  const last = lastAppliedPrefs.get(sessionKey) ?? {};
  const next = { ...last };
  if (incoming.model !== undefined && incoming.model !== last.model) {
    try {
      await backend.setModel?.(incoming.model);
      next.model = incoming.model;
    } catch (err: any) {
      send({ type: 'error', error: `Failed to switch model to "${incoming.model}": ${err?.message ?? err}` });
    }
  }
  if (incoming.effort !== undefined && incoming.effort !== last.effort) {
    try {
      await backend.setEffort?.(incoming.effort);
      next.effort = incoming.effort;
    } catch (err: any) {
      send({ type: 'error', error: `Failed to set effort "${incoming.effort}": ${err?.message ?? err}` });
    }
  }
  if (incoming.permissionMode !== undefined && incoming.permissionMode !== last.permissionMode) {
    try {
      await backend.setPermissionMode?.(incoming.permissionMode);
      next.permissionMode = incoming.permissionMode;
    } catch (err: any) {
      send({ type: 'error', error: `Failed to set permission mode "${incoming.permissionMode}": ${err?.message ?? err}` });
    }
  }
  lastAppliedPrefs.set(sessionKey, next);
}

/**
 * Test-mode override: when SHELF_TEST_MODE=1, every provider lookup returns
 * the same fake backend regardless of requested provider name. E2E specs
 * exercise renderer + main + agent-server wire chain without spinning up
 * real Claude/Copilot SDKs. Production builds set the env to undefined so
 * this branch is dead. See agent-core#5.
 */
const TEST_MODE = process.env.SHELF_TEST_MODE === '1';

/**
 * Project the app-skill tree to a provider's declared scan path. The provider
 * declares WHERE (`skillTarget`); the agent-server does the fs (provider-boundary
 * principle — providers never touch the filesystem). No-op for providers that
 * need no projection (skillTarget → undefined). Idempotent + atomic, so calling
 * it on every caps/send/reload is safe and collapses to one real creation.
 */
function ensureSkillsProjected(backend: ServerBackend, appId: string | undefined): void {
  const target = backend.skillTarget?.(appId);
  if (!target) return;
  const err = projectAppSkills(appId, target);
  if (err) serverLog('warn', 'skills', err);
}

/**
 * Create a provider's declared config-home BEFORE it spawns its CLI. Some CLIs
 * error if their config-home (auth / config / sessions dir) doesn't pre-exist —
 * codex is one, and a fresh appId with no app-level skills has nothing else that
 * would incidentally create it, so its caps spawn would fail (misreported as
 * "needs auth") without this. The provider only DECLARES the path (`configHome`);
 * the agent-server does the fs (provider-boundary principle). No-op for providers
 * whose CLI self-creates its home (copilot → undefined). Recursive + best-effort:
 * idempotent, so calling it on every caps/send is safe. See agent-providers#16.
 */
function ensureConfigHome(backend: ServerBackend, appId: string | undefined): void {
  const home = backend.configHome?.(appId);
  if (!home) return;
  try {
    fs.mkdirSync(home, { recursive: true });
  } catch (err: any) {
    serverLog('warn', 'config-home', `mkdir ${home} failed: ${err?.message ?? err}`);
  }
}

// Backend factory per provider. `Record<Provider, …>` makes this EXHAUSTIVE —
// adding a provider to the shared registry is a compile error until wired here.
const BACKEND_FACTORIES = {
  [CLAUDE_PROVIDER]: createClaudeBackend,
  [COPILOT_PROVIDER]: createCopilotBackend,
  [CODEX_PROVIDER]: createCodexBackend,
  [FAKE_PROVIDER]: () => createFakeBackend(FAKE_PROVIDER),
} satisfies Record<Provider, BackendFactory>;

const backendRegistry = createBackendRegistry(
  BACKEND_FACTORIES,
  TEST_MODE,
  (provider) => createFakeBackend(provider),
);

function getBackend(provider: Provider): ServerBackend {
  const backend = backendRegistry.get(provider);
  backend.bindSessionSend?.(send);
  return backend;
}

async function handleSend(msg: IncomingMessage) {
  if (msg.appId) lastAppId = msg.appId;
  const executionId = msg.executionId ?? newExecutionId();
  const executionSend = wrapSendForExecution(executionId, send);

  // A config-edit execution carries a structured edit instead of a prompt.
  const isConfigEdit = !!msg.configEdit;
  // An image-only execution has an empty prompt but DOES carry images — it's valid.
  // Every early-return below MUST emit `idle` (not just an error): the renderer
  // flipped to streaming on send, and without a terminal idle its spinner +
  // queue-flush latch wedge forever (the "whole conversation stuck" bug when an
  // image was sent with no text).
  const hasInput = !!msg.prompt || (msg.images?.length ?? 0) > 0 || (msg.attachments?.length ?? 0) > 0;
  if (!isConfigEdit && (!hasInput || !msg.cwd)) {
    executionSend({ type: 'error', error: !msg.cwd ? 'Missing cwd' : 'Missing prompt or images' });
    executionSend({ type: 'status', state: 'idle' });
    return;
  }
  if (isConfigEdit && !msg.cwd) {
    executionSend({ type: 'error', error: 'Missing cwd' });
    executionSend({ type: 'status', state: 'idle' });
    return;
  }
  const provider = msg.provider ?? CLAUDE_PROVIDER;
  let backend: ServerBackend;
  try {
    backend = getBackend(provider);
  } catch (err: any) {
    executionSend({ type: 'error', error: err.message });
    executionSend({ type: 'status', state: 'idle' });
    return;
  }
  activeBackend = backend;
  // Create the config-home + project app skills to the provider's scan path BEFORE
  // the execution spawns/uses the CLI, so session/new finds them and the CLI's config-home
  // exists. Central (agent-server owns the fs).
  ensureConfigHome(backend, msg.appId);
  ensureSkillsProjected(backend, msg.appId);

  // Hydrate persisted context once per execution — providers read fields they care
  // about (e.g. `lastSdkSessionId`) without touching disk themselves.
  const restoreContext = loadRestoreContextFor(provider, msg.sessionId);
  backend.bindSessionSend?.(wrapSendForContext(provider, msg.sessionId, send));

  // Pref diff only for prompt executions. A config-edit execution IS the change — it's
  // applied by the provider via input.configEdit; running the diff too would
  // double-apply (and emit a redundant capabilities).
  if (!isConfigEdit) {
    // Renderer-authoritative model/effort/permissionMode arrive in every send
    // payload. Orchestrator compares against last-applied for this session and
    // calls provider.setX? only on change. Per-sessionId so multi-tab doesn't
    // cross-contaminate.
    await applyPrefDiff(backend, msg.sessionId ?? '', {
      model: msg.model,
      effort: msg.effort,
      permissionMode: msg.permissionMode,
    });
  }

  const input: QueryInput = {
    prompt: msg.prompt ?? '',
    cwd: msg.cwd!,
    resume: msg.resume,
    permissionMode: msg.permissionMode,
    model: msg.model,
    effort: msg.effort,
    images: msg.images,
    attachments: msg.attachments,
    sessionId: msg.sessionId,
    configEdit: msg.configEdit,
    clientMsgId: msg.clientMsgId,
    appId: msg.appId,
    restoreContext,
  };

  const contextAware = wrapSendForContext(provider, msg.sessionId, executionSend);
  await backend.query(input, contextAware);

  // Post-execution: refresh account-level status (e.g. copilot credit) via the per-host
  // cache. Fire-and-forget + fail-quiet inside — must not delay readiness for the
  // next execution. Uses the base `send` (session-scoped status, executionId-less).
  void backend.refreshAccountStatus?.(modelCacheClient, send, input.appId);
}

async function handleStop() {
  if (!activeBackend) throw new Error('stop failed: no active backend');
  await activeBackend.stop();
}

// ── Idle-shutdown watchdog (ssh only) ────────────────────────────────────────
// `--idle-shutdown-min=N` is passed ONLY by the ssh spawn path (remote.ts): the
// remote host is not fate-shared with the client, so it keeps running while the
// laptop sleeps / app closes. When no `ping` arrives for N minutes, self-exit to
// free remote resources; the client respawns + resumes on reconnect. Fate-shared
// transports (local/docker/wsl) suspend with the host and never pass this arg.
// N is parsed as a float so tests can use sub-minute values. See connection-health#2.
const idleArg = process.argv.find((a) => a.startsWith('--idle-shutdown-min='));
const IDLE_SHUTDOWN_MS = idleArg ? Math.max(0, Number(idleArg.split('=')[1]) || 0) * 60_000 : 0;
let watchdogTimer: NodeJS.Timeout | undefined;
function resetWatchdog() {
  if (!IDLE_SHUTDOWN_MS) return;
  if (watchdogTimer) clearTimeout(watchdogTimer);
  watchdogTimer = setTimeout(() => {
    // Death path → stderr (NOT serverLog): main stopped pinging (likely gone), so a
    // wire log wouldn't deliver/flush anyway.
    console.error(`[agent-server] idle-shutdown: no ping for ${IDLE_SHUTDOWN_MS / 60_000}min — self-exiting`);
    // This IS a normal closure (a disconnect) — agent-server is alive, so run the
    // full shutdown (reap escaped detached tasks → dispose → exit), not a bare exit.
    void shutdown();
  }, IDLE_SHUTDOWN_MS);
}
resetWatchdog(); // arm from boot — if the client never pings, it's already gone

// Wire the app-tool bridge sender so in-process bridge tools can callMain().
initAppToolClient(send);

const rl = readline.createInterface({ input: process.stdin, terminal: false });

// ── Server-owned send queue ──────────────────────────────────────────────────
// The client (renderer) eager-sends every submission; THIS side owns the timing
// (排序 + 釋放時機). The queue serializes executions one-at-a-time (concurrent execution
// handlers would race on the provider backend's module-level state — activeExecutionSend
// / abortController / activeQuery / lastSessionId) AND is introspectable so we
// emit a snapshot the renderer mirrors. Logic lives in the pure `createSendQueue`
// factory (send-queue.ts, unit-tested). See message-queue-ownership design.
const sendQueue = createSendQueue<IncomingMessage>({
  handle: (msg) => handleSend(msg),
  // Session-level (no executionId) so main routes it to the `onQueue` sink.
  emitSnapshot: (items) => send({ type: 'queue', items }),
  // Dropped queued send → terminal idle on its executionId, or main's per-execution
  // generator (registered before the send was sent) hangs forever.
  terminateExecution: (executionId) => send({ type: 'status', state: 'idle', executionId } as OutgoingMessage),
  onHandleError: (msg, err) => {
    const tid = msg.executionId ?? '';
    send({ type: 'error', error: (err as any)?.message ?? String(err), executionId: tid } as OutgoingMessage);
    send({ type: 'status', state: 'idle', executionId: tid } as OutgoingMessage);
  },
  // Never silent: a cancel that didn't cleanly remove a queued item. 'cancel-
  // running' is a benign race (snapshot re-promotes); 'cancel-unknown' is a real
  // desync worth investigating → warn, routed to main's logger over the wire.
  onAnomaly: (reason, clientMsgId) => {
    serverLog('warn', 'send-queue', `${reason} clientMsgId=${clientMsgId}`);
  },
});

rl.on('line', (line) => {
  let msg: IncomingMessage;
  try {
    msg = JSON.parse(line);
  } catch {
    send({ type: 'error', error: 'Invalid JSON' });
    return;
  }

  switch (msg.type) {
    case 'send':
      sendQueue.enqueue(msg);
      break;
    case 'cancel_queued':
      if (typeof msg.clientMsgId === 'string') sendQueue.cancel(msg.clientMsgId);
      break;
    case 'stop':
      // ESC: clear the waiting queue (server is the queue authority now) +
      // interrupt the running execution. clear() emits the updated snapshot.
      sendQueue.clear();
      if (typeof msg.requestId === 'string') {
        void handleStop().then(
          () => send({ type: 'stop_result', requestId: msg.requestId!, ok: true }),
          (err) => {
            const error = (err as Error)?.message ?? String(err);
            serverLog('error', 'stop', `${error} reqId=${msg.requestId}`);
            send({ type: 'stop_result', requestId: msg.requestId!, ok: false, error });
          },
        );
      } else {
        // Legacy/non-RPC caller: still fail loud if provider cancellation fails.
        void handleStop().catch((err) => serverLog('error', 'stop', (err as Error)?.message ?? String(err)));
      }
      break;
    case 'ping':
      // Heartbeat: echo `seq` (client measures RTT on its own clock), refresh the
      // version-dir liveness lease the cleanup sweep reads (§5.9), and reset the
      // ssh idle-shutdown watchdog (the client is alive).
      send({ type: 'pong', seq: msg.seq });
      touchHeartbeats();
      resetWatchdog();
      break;
    case MEMORY_WIRE_TYPE.GET_USAGE:
      void reportMemoryUsage();
      break;
    case 'resolve_permission':
      if (activeBackend && msg.toolUseId !== undefined) {
        activeBackend.resolvePermission?.(msg.toolUseId, msg.allow ?? false, msg.message, msg.scope);
      }
      break;
    case 'resolve_picker':
      if (activeBackend && msg.pickerId !== undefined && msg.payload !== undefined) {
        activeBackend.resolvePicker?.(msg.pickerId, msg.payload);
      }
      break;
    case 'app_tool_result':
      // main's reply to an app_tool request — resolve the awaiting bridge tool.
      if (typeof msg.requestId === 'string') {
        resolveAppToolResult(msg.requestId, { ok: msg.ok ?? false, data: msg.data, error: msg.error });
      }
      break;
    case 'cache_reply':
      // dispatcher's answer to a cache_get (group E) — resolve the pending get.
      if (typeof msg.requestId === 'string') {
        resolveCacheReply(msg.requestId, (msg as any).hit ?? false, (msg as any).value);
      }
      break;
    case 'stop_task':
      // Fire-and-forget: the provider stops the task; the resulting
      // task_notification('stopped') flows back via the task_event lane.
      if (activeBackend && msg.taskId !== undefined) {
        void activeBackend.stopTask?.(msg.taskId);
      }
      break;
    case 'get_capabilities': {
      const provider = msg.provider ?? CLAUDE_PROVIDER;
      (async () => {
        try {
          const backend = getBackend(provider);
          // Create the config-home + project skills before caps — the CLI spawns
          // during gatherCapabilities (config-home providers), so both must exist
          // by then (codex errors if CODEX_HOME is absent → misreported as auth).
          ensureConfigHome(backend, msg.appId);
          ensureSkillsProjected(backend, msg.appId);
          const restoreContext = loadRestoreContextFor(provider, msg.sessionId);
          backend.bindSessionSend?.(wrapSendForContext(provider, msg.sessionId, send));
          const caps = await backend.gatherCapabilities?.(
            msg.cwd ?? process.cwd(),
            msg.sessionId,
            msg.customModels,
            msg.intent,
            modelCacheClient,
            msg.appId,
            restoreContext,
          );
          send({ type: 'capabilities', requestId: msg.requestId ?? '', ...(caps ?? {}) });
        } catch (err: any) {
          // Real data loss: gatherCapabilities threw → response carries only
          // `error`, and remote.ts resolves an all-empty caps (perm modes vanish).
          // Loud so the true cause (e.g. Copilot listModels network throw) is visible.
          serverLog('error', 'caps', `${provider} gatherCapabilities threw: ${err?.message ?? err} reqId=${msg.requestId ?? ''}`);
          send({ type: 'capabilities', requestId: msg.requestId ?? '', error: err?.message ?? String(err) });
        }
      })();
      break;
    }
    case 'store_credential': {
      const provider = msg.provider ?? CLAUDE_PROVIDER;
      (async () => {
        try {
          const backend = getBackend(provider);
          if (!backend.storeCredential) throw new Error(`Provider ${provider} does not accept API keys`);
          await backend.storeCredential(msg.key ?? '');
          send({ type: 'credential_stored', requestId: msg.requestId ?? '', ok: true });
        } catch (err: any) {
          send({ type: 'credential_stored', requestId: msg.requestId ?? '', ok: false, error: err?.message ?? String(err) });
        }
      })();
      break;
    }
    case 'clear_credential': {
      const provider = msg.provider ?? CLAUDE_PROVIDER;
      (async () => {
        try {
          const backend = getBackend(provider);
          if (!backend.clearCredential) throw new Error(`Provider ${provider} has no credential to clear`);
          await backend.clearCredential();
          send({ type: 'credential_cleared', requestId: msg.requestId ?? '', ok: true });
        } catch (err: any) {
          send({ type: 'credential_cleared', requestId: msg.requestId ?? '', ok: false, error: err?.message ?? String(err) });
        }
      })();
      break;
    }
    case 'read_task_output': {
      const provider = msg.provider ?? CLAUDE_PROVIDER;
      (async () => {
        try {
          const backend = getBackend(provider);
          if (!backend.readTaskOutput) throw new Error(`Provider ${provider} does not support reading task output`);
          const content = await backend.readTaskOutput(msg.taskId ?? '');
          send({ type: 'task_output', requestId: msg.requestId ?? '', content });
        } catch (err: any) {
          send({ type: 'task_output', requestId: msg.requestId ?? '', error: err?.message ?? String(err) });
        }
      })();
      break;
    }
    case 'reload_skills':
      // App-level skills changed: main refreshed the L1 canonical tree. Re-project
      // each provider's L2 target (central — agent-server owns the fs; a no-op for
      // symlink providers since the live source is already followed, real work for
      // copy-mode), THEN tell EVERY provider to re-scan on its live session. App
      // skills are app-global, not per-session; each reload is best-effort + no-op
      // without a live session. Emit a `skills_reloaded` result via the BASE send.
      for (const b of backendRegistry.values()) ensureSkillsProjected(b, lastAppId);
      for (const b of backendRegistry.values()) {
        void b.reloadSkills?.().then((r) => {
          if (r && r.reloaded) send({ type: 'skills_reloaded', ok: r.ok, ...(r.error ? { error: r.error } : {}) });
        });
      }
      break;
    case 'start_login': {
      // Interactive device-flow login (fire-and-forget). The provider spawns its
      // CLI login, forwards the parsed prompt via the BASE `send` (executionId-less,
      // like auth_required), and emits auth_login_done on exit. See
      // features copilot-device-login.
      const provider = msg.provider ?? COPILOT_PROVIDER;
      try {
        const backend = getBackend(provider);
        if (!backend.startLogin) {
          send({ type: 'auth_login_done', provider, ok: false, error: `Provider ${provider} has no interactive login` });
          break;
        }
        backend.startLogin(msg.cwd ?? process.cwd(), send);
      } catch (err: any) {
        send({ type: 'auth_login_done', provider, ok: false, error: err?.message ?? String(err) });
      }
      break;
    }
    case 'cancel_login':
      // Best-effort: cancel a running login on whichever backend is active.
      activeBackend?.cancelLogin?.();
      break;
    case 'reconnect': {
      // Post-login re-init (Gap C): drop the provider's live ACP connection so the
      // next caps/execution respawns and re-reads the config-home credentials the device-
      // login just wrote. No-op for providers without a long-lived process. main
      // sends this right before re-fetching capabilities (order preserved by the
      // FIFO stdin stream — reconnect runs synchronously before get_capabilities).
      const provider = msg.provider ?? COPILOT_PROVIDER;
      try {
        getBackend(provider).reconnect?.();
      } catch (err: any) {
        serverLog('warn', 'exec', `reconnect failed: ${err?.message ?? err}`, { provider });
      }
      break;
    }
    case 'clear_context': {
      if (msg.sessionId) {
        deleteContext(msg.sessionId);
        // Tell every provider that has cached state for this session to drop it,
        // so they don't try to resume from a now-deleted lastSdkSessionId on
        // the next execution. Sync per-backend call — they just clear in-memory refs.
        for (const b of backendRegistry.values()) b.resetSession?.(msg.sessionId);
      }
      break;
    }
    default: {
      // Fail-loud on an unknown wire command instead of silently dropping it —
      // a main↔agent-server protocol drift must leave a trace, not vanish.
      serverLog('warn', 'exec', 'unknown incoming message type — ignored', { type: (msg as any)?.type });
      break;
    }
  }
});

// Every NORMAL agent-server closure funnels through shutdown(): reap escaped
// detached tasks, dispose backends, exit. Called from BOTH the stdin-close handler
// and the idle watchdog; `shuttingDown` makes it idempotent (both can fire). It
// ALWAYS reaps — a closure while we're alive is a real end of session (no
// reconnect). Only an ABNORMAL closure (agent-server itself died) skips this →
// crash net (Phase 2). Reap timeout is bounded so a hung provider RPC can't stall.
let shuttingDown = false;
const REAP_TIMEOUT_MS = 2000;

async function shutdown(): Promise<void> {
  if (shuttingDown) return;
  shuttingDown = true;
  await performShutdown({
    backends: backendRegistry.values(),
    reapTimeoutMs: REAP_TIMEOUT_MS,
    log: (level, msg) => serverLog(level, 'reaper', msg),
    // Normal closure: we just reaped our own detached tasks, so drop our crash-net
    // lease — next launch must NOT sweep a session that shut down cleanly.
    exit: () => {
      removeSessionLease(SHELF_SESSION);
      process.exit(0);
    },
  });
}

rl.on('close', () => {
  void shutdown();
});

cleanupOldContexts();
// Reclaim stale ~/.shelf dirs via heartbeat-lease (replaces the old eager
// "delete every other version" cleanup that thrashed on shared remotes — see
// #70 / §5.9). currentVersion = our own deploy dir name. lastAppId is unknown
// until the first send, so the apps sweep keeps any fresh-lease dir this pass.
runCleanupSweep(path.basename(__dirname), lastAppId);
// Phase-2 crash net: reap detached tasks left by a PRIOR agent-server that died
// abnormally (Linux only — no-op where /proc is absent). Best-effort + BEFORE
// registering our own lease, so we never sweep ourselves. A normal shutdown
// removes its own lease (it already reaped), so a lingering lease ⇒ a crash.
try {
  sweepDeadSessions((level, msg) => serverLog(level, 'session-sweep', msg));
} catch (err: any) {
  serverLog('warn', 'session-sweep', `startup sweep failed: ${err?.message ?? err}`);
}
writeLease({ session: SHELF_SESSION, ownerPid: process.pid, ownerStartTime: readProcStartTime(process.pid), createdAt: Date.now() });
send({ type: 'ready' });
