import * as readline from 'readline';
import { createClaudeBackend } from './providers/claude';
import { createCopilotBackend } from './providers/copilot';
import { createFakeBackend } from './providers/fake';
import { deleteContext, cleanupOldContexts } from './context-store';
import { loadRestoreContextFor, newTurnId, wrapSendForContext, wrapSendForTurn } from './orchestrator';
import type { OutgoingMessage, QueryInput, ServerBackend, PickerResolvePayload } from './providers/types';
import type { ProviderModel } from '../src/shared/types';

type Provider = 'claude' | 'copilot';

interface IncomingMessage {
  type: 'send' | 'stop' | 'ping' | 'resolve_permission' | 'resolve_picker' | 'get_capabilities' | 'store_credential' | 'clear_credential' | 'clear_context';
  provider?: Provider;
  /**
   * For `type: 'send'`: turnId generated by main side so it can pre-register
   * the per-turn event dispatcher before we start emitting. Missing turnId
   * falls back to a freshly-generated one — defensive only; main always sets
   * it in the current architecture.
   */
  turnId?: string;
  prompt?: string;
  cwd?: string;
  resume?: string;
  permissionMode?: string;
  model?: string;
  effort?: string;
  images?: string[];
  sessionId?: string;
  toolUseId?: string;
  allow?: boolean;
  /** resolve_picker payload — picker id minted by provider, payload carries
   * index-aligned answers or { cancelled: true } (see PickerResolvePayload). */
  pickerId?: string;
  payload?: PickerResolvePayload;
  message?: string;
  requestId?: string;
  key?: string;
  customModels?: ProviderModel[];
  scope?: 'once' | 'session';
}

function send(msg: OutgoingMessage) {
  process.stdout.write(JSON.stringify(msg) + '\n');
}

const backends = new Map<Provider, ServerBackend>();
let activeBackend: ServerBackend | null = null;

/**
 * Per-session pref cache. Orchestrator drives "did renderer change pref X
 * since last send?" diff detection — calls backend.setModel/setEffort/
 * setPermissionMode only on change. Keyed by sessionId so multi-tab
 * scenarios don't cross-contaminate each other's diff state (which the
 * old per-provider-singleton closure cache in Copilot did suffer from).
 */
const lastAppliedPrefs = new Map<string, { model?: string; effort?: string; permissionMode?: string }>();

async function applyPrefDiff(
  backend: ServerBackend,
  sessionKey: string,
  incoming: { model?: string; effort?: string; permissionMode?: string },
): Promise<void> {
  const last = lastAppliedPrefs.get(sessionKey) ?? {};
  const next = { ...last };
  if (incoming.model !== undefined && incoming.model !== last.model) {
    try { await backend.setModel?.(incoming.model); } catch (err: any) {
      send({ type: 'error', error: `Failed to switch model to "${incoming.model}": ${err?.message ?? err}` });
    }
    next.model = incoming.model;
  }
  if (incoming.effort !== undefined && incoming.effort !== last.effort) {
    try { await backend.setEffort?.(incoming.effort); } catch (err: any) {
      send({ type: 'error', error: `Failed to set effort "${incoming.effort}": ${err?.message ?? err}` });
    }
    next.effort = incoming.effort;
  }
  if (incoming.permissionMode !== undefined && incoming.permissionMode !== last.permissionMode) {
    try { await backend.setPermissionMode?.(incoming.permissionMode); } catch (err: any) {
      send({ type: 'error', error: `Failed to set permission mode "${incoming.permissionMode}": ${err?.message ?? err}` });
    }
    next.permissionMode = incoming.permissionMode;
  }
  lastAppliedPrefs.set(sessionKey, next);
}

/**
 * Test-mode override: when SHELF_TEST_MODE=1, every provider lookup returns
 * the same fake backend regardless of requested provider name. E2E specs
 * exercise renderer + main + agent-server wire chain without spinning up
 * real Claude/Copilot SDKs. Production builds set the env to undefined so
 * this branch is dead. See `.agent/features/fake-provider-e2e.md`.
 */
const TEST_MODE = process.env.SHELF_TEST_MODE === '1';

function getBackend(provider: Provider): ServerBackend {
  const key = (TEST_MODE ? 'fake' : provider) as Provider;
  let b = backends.get(key);
  if (b) return b;
  if (TEST_MODE) {
    b = createFakeBackend();
  } else {
    switch (provider) {
      case 'claude':
        b = createClaudeBackend();
        break;
      case 'copilot':
        b = createCopilotBackend();
        break;
    }
  }
  backends.set(key, b);
  return b;
}

async function handleSend(msg: IncomingMessage) {
  if (!msg.prompt || !msg.cwd) {
    send({ type: 'error', error: 'Missing prompt or cwd' });
    return;
  }
  const provider = msg.provider ?? 'claude';
  let backend: ServerBackend;
  try {
    backend = getBackend(provider);
  } catch (err: any) {
    send({ type: 'error', error: err.message });
    return;
  }
  activeBackend = backend;

  // Hydrate persisted context once per turn — providers read fields they care
  // about (e.g. `lastSdkSessionId`) without touching disk themselves.
  const restoreContext = loadRestoreContextFor(provider, msg.sessionId);

  // Pref diff: renderer-authoritative model/effort/permissionMode arrive in
  // every send payload. Orchestrator compares against last-applied for this
  // session and calls provider.setX? only on change. Provider's own setX
  // implementations are imperative ("apply this now") — diff is here, not
  // there. Per-sessionId so multi-tab doesn't cross-contaminate.
  await applyPrefDiff(backend, msg.sessionId ?? '', {
    model: msg.model,
    effort: msg.effort,
    permissionMode: msg.permissionMode,
  });

  const input: QueryInput = {
    prompt: msg.prompt,
    cwd: msg.cwd,
    resume: msg.resume,
    permissionMode: msg.permissionMode,
    model: msg.model,
    effort: msg.effort,
    images: msg.images,
    sessionId: msg.sessionId,
    restoreContext,
  };

  // Compose send wrappers. Order matters: provider's `send(msg)` first hits
  // context-aware (intercepts `context_patch` and writes to disk, skipping
  // forward), then turn-aware (stamps `turnId` envelope onto everything that
  // does get forwarded). Routing on the main side keys off this turnId.
  //
  // turnId is generated by the main process so it can register the per-turn
  // dispatcher BEFORE this send arrives — eliminates the race window where
  // our first emit could land before main knows about the turn.
  const turnId = msg.turnId ?? newTurnId();
  const turnAware = wrapSendForTurn(turnId, send);
  const contextAware = wrapSendForContext(provider, msg.sessionId, turnAware);
  await backend.query(input, contextAware);
}

async function handleStop() {
  if (activeBackend) {
    await activeBackend.stop();
  }
}

const rl = readline.createInterface({ input: process.stdin, terminal: false });

// Serialize send handling. `rl.on('line')` fires sync per stdin line and the
// previous `handleSend` is async — without serialization, two sends can run
// concurrently, racing on the provider backend's module-level state
// (currentSend / abortController / activeQuery / lastSessionId). The race
// shows up when the renderer flushes a queued message ~50ms after the
// previous turn's idle: turn 1's claude.ts `finally` hasn't run yet, turn 2
// overwrites the module state, then turn 1's finally nukes it — turn 2's
// sdkQuery silently yields 0 events.
let sendChain: Promise<void> = Promise.resolve();

rl.on('line', (line) => {
  let msg: IncomingMessage;
  try {
    msg = JSON.parse(line);
  } catch {
    send({ type: 'error', error: 'Invalid JSON' });
    return;
  }

  switch (msg.type) {
    case 'send':
      sendChain = sendChain
        .then(() => handleSend(msg))
        .catch((err) => {
          send({ type: 'error', error: err?.message ?? String(err) });
        });
      break;
    case 'stop':
      handleStop();
      break;
    case 'ping':
      send({ type: 'pong' });
      break;
    case 'resolve_permission':
      if (activeBackend && msg.toolUseId !== undefined) {
        activeBackend.resolvePermission?.(msg.toolUseId, msg.allow ?? false, msg.message, msg.scope);
      }
      break;
    case 'resolve_picker':
      if (activeBackend && msg.pickerId !== undefined && msg.payload !== undefined) {
        activeBackend.resolvePicker?.(msg.pickerId, msg.payload);
      }
      break;
    case 'get_capabilities': {
      const provider = msg.provider ?? 'claude';
      (async () => {
        try {
          const backend = getBackend(provider);
          const caps = await backend.gatherCapabilities?.(msg.cwd ?? process.cwd(), msg.sessionId, msg.customModels);
          send({ type: 'capabilities', requestId: msg.requestId ?? '', ...(caps ?? {}) });
        } catch (err: any) {
          send({ type: 'capabilities', requestId: msg.requestId ?? '', error: err?.message ?? String(err) });
        }
      })();
      break;
    }
    case 'store_credential': {
      const provider = msg.provider ?? 'claude';
      (async () => {
        try {
          const backend = getBackend(provider);
          if (!backend.storeCredential) throw new Error(`Provider ${provider} does not accept API keys`);
          await backend.storeCredential(msg.key ?? '');
          send({ type: 'credential_stored', requestId: msg.requestId ?? '', ok: true });
        } catch (err: any) {
          send({ type: 'credential_stored', requestId: msg.requestId ?? '', ok: false, error: err?.message ?? String(err) });
        }
      })();
      break;
    }
    case 'clear_credential': {
      const provider = msg.provider ?? 'claude';
      (async () => {
        try {
          const backend = getBackend(provider);
          if (!backend.clearCredential) throw new Error(`Provider ${provider} has no credential to clear`);
          await backend.clearCredential();
          send({ type: 'credential_cleared', requestId: msg.requestId ?? '', ok: true });
        } catch (err: any) {
          send({ type: 'credential_cleared', requestId: msg.requestId ?? '', ok: false, error: err?.message ?? String(err) });
        }
      })();
      break;
    }
    case 'clear_context': {
      if (msg.sessionId) {
        deleteContext(msg.sessionId);
        // Tell every provider that has cached state for this session to drop it,
        // so they don't try to resume from a now-deleted lastSdkSessionId on
        // the next turn. Sync per-backend call — they just clear in-memory refs.
        for (const b of backends.values()) b.resetSession?.(msg.sessionId);
      }
      break;
    }
  }
});

rl.on('close', () => {
  for (const b of backends.values()) b.dispose();
  process.exit(0);
});

cleanupOldContexts();
send({ type: 'ready' });
