import * as readline from 'readline';
import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';
import { createClaudeBackend } from './providers/claude';
import { createCopilotBackend } from './providers/copilot';
import { createFakeBackend } from './providers/fake';
import { deleteContext, cleanupOldContexts } from './context-store';
import { runCleanupSweep } from './cleanup';
import { loadRestoreContextFor, newTurnId, wrapSendForContext, wrapSendForTurn } from './orchestrator';
import type { OutgoingMessage, QueryInput, ServerBackend, PickerResolvePayload } from './providers/types';
import type { ProviderModel } from '@shared/types';

type Provider = 'claude' | 'copilot';

interface IncomingMessage {
  type: 'send' | 'stop' | 'ping' | 'resolve_permission' | 'resolve_picker' | 'get_capabilities' | 'store_credential' | 'clear_credential' | 'clear_context' | 'read_task_output';
  provider?: Provider;
  /**
   * For `type: 'send'`: turnId generated by main side so it can pre-register
   * the per-turn event dispatcher before we start emitting. Missing turnId
   * falls back to a freshly-generated one — defensive only; main always sets
   * it in the current architecture.
   */
  turnId?: string;
  prompt?: string;
  cwd?: string;
  resume?: string;
  permissionMode?: string;
  model?: string;
  effort?: string;
  images?: string[];
  sessionId?: string;
  /** For `type: 'send'`: a structured config edit (picker / status-bar). When
   *  present, the provider applies it + emits a divider instead of running a
   *  query — prompt is empty for these turns. */
  configEdit?: { key: 'model' | 'effort' | 'permissionMode'; value: string };
  toolUseId?: string;
  allow?: boolean;
  /** For `type: 'ping'`: client heartbeat sequence, echoed back in pong for RTT. */
  seq?: number;
  /** For `type: 'send'`: app-instance id — names this app's projected skills dir
   *  at `~/.shelf/apps/<appId>/skills` (see DECISION #70). */
  appId?: string;
  /** resolve_picker payload — picker id minted by provider, payload carries
   * index-aligned answers or { cancelled: true } (see PickerResolvePayload). */
  pickerId?: string;
  payload?: PickerResolvePayload;
  message?: string;
  requestId?: string;
  key?: string;
  customModels?: ProviderModel[];
  scope?: 'once' | 'session';
  /** For `type: 'read_task_output'`: which background task's remote output_file to read. */
  taskId?: string;
  /**
   * For `type: 'get_capabilities'`: renderer's saved prefs forwarded so
   * session-stateful providers (Copilot) can seed currentModel/currentEffort/
   * currentPermissionMode closures before reporting `current*` back.
   */
  intent?: { model?: string; effort?: string; permissionMode?: string };
}

function send(msg: OutgoingMessage) {
  process.stdout.write(JSON.stringify(msg) + '\n');
}

// Last appId seen on a `send` — names this app's projected skills dir; used to
// keep its `.heartbeat` lease fresh + protect it from the startup sweep.
let lastAppId: string | undefined;

/**
 * Refresh the `.heartbeat` leases the cleanup sweep reads (see #70 / §5.9):
 * the version dir (when running under `~/.shelf/agent-server/<version>/`; local
 * dist runs skip it) and this app's `~/.shelf/apps/<appId>/` dir. Best-effort —
 * never break the pong reply.
 */
function touchHeartbeats(): void {
  try {
    if (/\.shelf\/agent-server\//.test(__dirname)) {
      fs.writeFileSync(path.join(__dirname, '.heartbeat'), '');
    }
  } catch { /* version lease best-effort */ }
  try {
    if (lastAppId) {
      const appDir = path.join(os.homedir(), '.shelf', 'apps', lastAppId);
      fs.mkdirSync(appDir, { recursive: true });
      fs.writeFileSync(path.join(appDir, '.heartbeat'), '');
    }
  } catch { /* app lease best-effort */ }
}

const backends = new Map<Provider, ServerBackend>();
let activeBackend: ServerBackend | null = null;

/**
 * Per-session pref cache. Orchestrator drives "did renderer change pref X
 * since last send?" diff detection — calls backend.setModel/setEffort/
 * setPermissionMode only on change. Keyed by sessionId so multi-tab
 * scenarios don't cross-contaminate each other's diff state (which the
 * old per-provider-singleton closure cache in Copilot did suffer from).
 */
const lastAppliedPrefs = new Map<string, { model?: string; effort?: string; permissionMode?: string }>();

async function applyPrefDiff(
  backend: ServerBackend,
  sessionKey: string,
  incoming: { model?: string; effort?: string; permissionMode?: string },
): Promise<void> {
  // Cache update is gated on apply success — a failed setX must not record
  // the requested value as "applied" or the next turn's diff would skip the
  // retry (silently leaving the SDK on the prior value while the cache
  // pretends the switch happened).
  const last = lastAppliedPrefs.get(sessionKey) ?? {};
  const next = { ...last };
  if (incoming.model !== undefined && incoming.model !== last.model) {
    try {
      await backend.setModel?.(incoming.model);
      next.model = incoming.model;
    } catch (err: any) {
      send({ type: 'error', error: `Failed to switch model to "${incoming.model}": ${err?.message ?? err}` });
    }
  }
  if (incoming.effort !== undefined && incoming.effort !== last.effort) {
    try {
      await backend.setEffort?.(incoming.effort);
      next.effort = incoming.effort;
    } catch (err: any) {
      send({ type: 'error', error: `Failed to set effort "${incoming.effort}": ${err?.message ?? err}` });
    }
  }
  if (incoming.permissionMode !== undefined && incoming.permissionMode !== last.permissionMode) {
    try {
      await backend.setPermissionMode?.(incoming.permissionMode);
      next.permissionMode = incoming.permissionMode;
    } catch (err: any) {
      send({ type: 'error', error: `Failed to set permission mode "${incoming.permissionMode}": ${err?.message ?? err}` });
    }
  }
  lastAppliedPrefs.set(sessionKey, next);
}

/**
 * Test-mode override: when SHELF_TEST_MODE=1, every provider lookup returns
 * the same fake backend regardless of requested provider name. E2E specs
 * exercise renderer + main + agent-server wire chain without spinning up
 * real Claude/Copilot SDKs. Production builds set the env to undefined so
 * this branch is dead. See DECISIONS #58.
 */
const TEST_MODE = process.env.SHELF_TEST_MODE === '1';

function getBackend(provider: Provider): ServerBackend {
  const key = (TEST_MODE ? 'fake' : provider) as Provider;
  let b = backends.get(key);
  if (b) return b;
  if (TEST_MODE) {
    b = createFakeBackend();
  } else {
    switch (provider) {
      case 'claude':
        b = createClaudeBackend();
        break;
      case 'copilot':
        b = createCopilotBackend();
        break;
    }
  }
  backends.set(key, b);
  return b;
}

async function handleSend(msg: IncomingMessage) {
  if (msg.appId) lastAppId = msg.appId;
  const turnId = msg.turnId ?? newTurnId();
  const turnSend = wrapSendForTurn(turnId, send);

  // A config-edit turn carries a structured edit instead of a prompt.
  const isConfigEdit = !!msg.configEdit;
  // An image-only turn has an empty prompt but DOES carry images — it's valid.
  // Every early-return below MUST emit `idle` (not just an error): the renderer
  // flipped to streaming on send, and without a terminal idle its spinner +
  // queue-flush latch wedge forever (the "whole conversation stuck" bug when an
  // image was sent with no text).
  const hasInput = !!msg.prompt || (msg.images?.length ?? 0) > 0;
  if (!isConfigEdit && (!hasInput || !msg.cwd)) {
    turnSend({ type: 'error', error: !msg.cwd ? 'Missing cwd' : 'Missing prompt or images' });
    turnSend({ type: 'status', state: 'idle' });
    return;
  }
  if (isConfigEdit && !msg.cwd) {
    turnSend({ type: 'error', error: 'Missing cwd' });
    turnSend({ type: 'status', state: 'idle' });
    return;
  }
  const provider = msg.provider ?? 'claude';
  let backend: ServerBackend;
  try {
    backend = getBackend(provider);
  } catch (err: any) {
    turnSend({ type: 'error', error: err.message });
    return;
  }
  activeBackend = backend;

  // Hydrate persisted context once per turn — providers read fields they care
  // about (e.g. `lastSdkSessionId`) without touching disk themselves.
  const restoreContext = loadRestoreContextFor(provider, msg.sessionId);

  // Pref diff only for prompt turns. A config-edit turn IS the change — it's
  // applied by the provider via input.configEdit; running the diff too would
  // double-apply (and emit a redundant capabilities).
  if (!isConfigEdit) {
    // Renderer-authoritative model/effort/permissionMode arrive in every send
    // payload. Orchestrator compares against last-applied for this session and
    // calls provider.setX? only on change. Per-sessionId so multi-tab doesn't
    // cross-contaminate.
    await applyPrefDiff(backend, msg.sessionId ?? '', {
      model: msg.model,
      effort: msg.effort,
      permissionMode: msg.permissionMode,
    });
  }

  const input: QueryInput = {
    prompt: msg.prompt ?? '',
    cwd: msg.cwd!,
    resume: msg.resume,
    permissionMode: msg.permissionMode,
    model: msg.model,
    effort: msg.effort,
    images: msg.images,
    sessionId: msg.sessionId,
    configEdit: msg.configEdit,
    appId: msg.appId,
    restoreContext,
  };

  const contextAware = wrapSendForContext(provider, msg.sessionId, turnSend);
  await backend.query(input, contextAware);
}

async function handleStop() {
  if (activeBackend) {
    await activeBackend.stop();
  }
}

const rl = readline.createInterface({ input: process.stdin, terminal: false });

// Serialize send handling. `rl.on('line')` fires sync per stdin line and the
// previous `handleSend` is async — without serialization, two sends can run
// concurrently, racing on the provider backend's module-level state
// (currentSend / abortController / activeQuery / lastSessionId). The race
// shows up when the renderer flushes a queued message ~50ms after the
// previous turn's idle: turn 1's claude.ts `finally` hasn't run yet, turn 2
// overwrites the module state, then turn 1's finally nukes it — turn 2's
// sdkQuery silently yields 0 events.
let sendChain: Promise<void> = Promise.resolve();

rl.on('line', (line) => {
  let msg: IncomingMessage;
  try {
    msg = JSON.parse(line);
  } catch {
    send({ type: 'error', error: 'Invalid JSON' });
    return;
  }

  switch (msg.type) {
    case 'send':
      sendChain = sendChain
        .then(() => handleSend(msg))
        .catch((err) => {
          const tid = msg.turnId ?? '';
          send({ type: 'error', error: err?.message ?? String(err), turnId: tid } as any);
        });
      break;
    case 'stop':
      handleStop();
      break;
    case 'ping':
      // Heartbeat: echo `seq` (client measures RTT on its own clock) and refresh
      // the version-dir liveness lease the cleanup sweep reads. See §5.9.
      send({ type: 'pong', seq: msg.seq });
      touchHeartbeats();
      break;
    case 'resolve_permission':
      if (activeBackend && msg.toolUseId !== undefined) {
        activeBackend.resolvePermission?.(msg.toolUseId, msg.allow ?? false, msg.message, msg.scope);
      }
      break;
    case 'resolve_picker':
      if (activeBackend && msg.pickerId !== undefined && msg.payload !== undefined) {
        activeBackend.resolvePicker?.(msg.pickerId, msg.payload);
      }
      break;
    case 'get_capabilities': {
      const provider = msg.provider ?? 'claude';
      (async () => {
        try {
          const backend = getBackend(provider);
          const caps = await backend.gatherCapabilities?.(msg.cwd ?? process.cwd(), msg.sessionId, msg.customModels, msg.intent);
          send({ type: 'capabilities', requestId: msg.requestId ?? '', ...(caps ?? {}) });
        } catch (err: any) {
          send({ type: 'capabilities', requestId: msg.requestId ?? '', error: err?.message ?? String(err) });
        }
      })();
      break;
    }
    case 'store_credential': {
      const provider = msg.provider ?? 'claude';
      (async () => {
        try {
          const backend = getBackend(provider);
          if (!backend.storeCredential) throw new Error(`Provider ${provider} does not accept API keys`);
          await backend.storeCredential(msg.key ?? '');
          send({ type: 'credential_stored', requestId: msg.requestId ?? '', ok: true });
        } catch (err: any) {
          send({ type: 'credential_stored', requestId: msg.requestId ?? '', ok: false, error: err?.message ?? String(err) });
        }
      })();
      break;
    }
    case 'clear_credential': {
      const provider = msg.provider ?? 'claude';
      (async () => {
        try {
          const backend = getBackend(provider);
          if (!backend.clearCredential) throw new Error(`Provider ${provider} has no credential to clear`);
          await backend.clearCredential();
          send({ type: 'credential_cleared', requestId: msg.requestId ?? '', ok: true });
        } catch (err: any) {
          send({ type: 'credential_cleared', requestId: msg.requestId ?? '', ok: false, error: err?.message ?? String(err) });
        }
      })();
      break;
    }
    case 'read_task_output': {
      const provider = msg.provider ?? 'claude';
      (async () => {
        try {
          const backend = getBackend(provider);
          if (!backend.readTaskOutput) throw new Error(`Provider ${provider} does not support reading task output`);
          const content = await backend.readTaskOutput(msg.taskId ?? '');
          send({ type: 'task_output', requestId: msg.requestId ?? '', content });
        } catch (err: any) {
          send({ type: 'task_output', requestId: msg.requestId ?? '', error: err?.message ?? String(err) });
        }
      })();
      break;
    }
    case 'clear_context': {
      if (msg.sessionId) {
        deleteContext(msg.sessionId);
        // Tell every provider that has cached state for this session to drop it,
        // so they don't try to resume from a now-deleted lastSdkSessionId on
        // the next turn. Sync per-backend call — they just clear in-memory refs.
        for (const b of backends.values()) b.resetSession?.(msg.sessionId);
      }
      break;
    }
  }
});

rl.on('close', () => {
  for (const b of backends.values()) b.dispose();
  process.exit(0);
});

cleanupOldContexts();
// Reclaim stale ~/.shelf dirs via heartbeat-lease (replaces the old eager
// "delete every other version" cleanup that thrashed on shared remotes — see
// #70 / §5.9). currentVersion = our own deploy dir name. lastAppId is unknown
// until the first send, so the apps sweep keeps any fresh-lease dir this pass.
runCleanupSweep(path.basename(__dirname), lastAppId);
send({ type: 'ready' });
