import * as readline from 'readline';
import { createClaudeBackend } from './providers/claude';
import { createCopilotBackend } from './providers/copilot';
import { deleteContext, cleanupOldContexts } from './context-store';
import { loadRestoreContextFor, newTurnId, wrapSendForContext, wrapSendForTurn } from './orchestrator';
import type { OutgoingMessage, QueryInput, ServerBackend } from './providers/types';
import type { ProviderModel } from '../src/shared/types';

type Provider = 'claude' | 'copilot';

interface IncomingMessage {
  type: 'send' | 'stop' | 'ping' | 'resolve_permission' | 'get_capabilities' | 'store_credential' | 'clear_credential' | 'clear_context' | 'slash_command';
  provider?: Provider;
  /**
   * For `type: 'send'`: turnId generated by main side so it can pre-register
   * the per-turn event dispatcher before we start emitting. Missing turnId
   * falls back to a freshly-generated one — defensive only; main always sets
   * it in the current architecture.
   */
  turnId?: string;
  prompt?: string;
  cwd?: string;
  resume?: string;
  permissionMode?: string;
  model?: string;
  effort?: string;
  images?: string[];
  sessionId?: string;
  toolUseId?: string;
  allow?: boolean;
  message?: string;
  requestId?: string;
  key?: string;
  cmd?: string;
  args?: string;
  customModels?: ProviderModel[];
  scope?: 'once' | 'session';
}

function send(msg: OutgoingMessage) {
  process.stdout.write(JSON.stringify(msg) + '\n');
}

const backends = new Map<Provider, ServerBackend>();
let activeBackend: ServerBackend | null = null;

function getBackend(provider: Provider): ServerBackend {
  let b = backends.get(provider);
  if (b) return b;
  switch (provider) {
    case 'claude':
      b = createClaudeBackend();
      break;
    case 'copilot':
      b = createCopilotBackend();
      break;
  }
  backends.set(provider, b);
  return b;
}

async function handleSend(msg: IncomingMessage) {
  if (!msg.prompt || !msg.cwd) {
    send({ type: 'error', error: 'Missing prompt or cwd' });
    return;
  }
  const provider = msg.provider ?? 'claude';
  let backend: ServerBackend;
  try {
    backend = getBackend(provider);
  } catch (err: any) {
    send({ type: 'error', error: err.message });
    return;
  }
  activeBackend = backend;

  // Hydrate persisted context once per turn — providers read fields they care
  // about (e.g. `lastSdkSessionId`) without touching disk themselves.
  const restoreContext = loadRestoreContextFor(provider, msg.sessionId);

  const input: QueryInput = {
    prompt: msg.prompt,
    cwd: msg.cwd,
    resume: msg.resume,
    permissionMode: msg.permissionMode,
    model: msg.model,
    effort: msg.effort,
    images: msg.images,
    sessionId: msg.sessionId,
    restoreContext,
  };

  // Compose send wrappers. Order matters: provider's `send(msg)` first hits
  // context-aware (intercepts `context_patch` and writes to disk, skipping
  // forward), then turn-aware (stamps `turnId` envelope onto everything that
  // does get forwarded). Routing on the main side keys off this turnId.
  //
  // turnId is generated by the main process so it can register the per-turn
  // dispatcher BEFORE this send arrives — eliminates the race window where
  // our first emit could land before main knows about the turn.
  const turnId = msg.turnId ?? newTurnId();
  const turnAware = wrapSendForTurn(turnId, send);
  const contextAware = wrapSendForContext(provider, msg.sessionId, turnAware);
  await backend.query(input, contextAware);
}

async function handleStop() {
  if (activeBackend) {
    await activeBackend.stop();
  }
}

const rl = readline.createInterface({ input: process.stdin, terminal: false });

// Serialize send handling. `rl.on('line')` fires sync per stdin line and the
// previous `handleSend` is async — without serialization, two sends can run
// concurrently, racing on the provider backend's module-level state
// (currentSend / abortController / activeQuery / lastSessionId). The race
// shows up when the renderer flushes a queued message ~50ms after the
// previous turn's idle: turn 1's claude.ts `finally` hasn't run yet, turn 2
// overwrites the module state, then turn 1's finally nukes it — turn 2's
// sdkQuery silently yields 0 events.
let sendChain: Promise<void> = Promise.resolve();

rl.on('line', (line) => {
  let msg: IncomingMessage;
  try {
    msg = JSON.parse(line);
  } catch {
    send({ type: 'error', error: 'Invalid JSON' });
    return;
  }

  switch (msg.type) {
    case 'send':
      sendChain = sendChain
        .then(() => handleSend(msg))
        .catch((err) => {
          send({ type: 'error', error: err?.message ?? String(err) });
        });
      break;
    case 'stop':
      handleStop();
      break;
    case 'ping':
      send({ type: 'pong' });
      break;
    case 'resolve_permission':
      if (activeBackend && msg.toolUseId !== undefined) {
        activeBackend.resolvePermission?.(msg.toolUseId, msg.allow ?? false, msg.message, msg.scope);
      }
      break;
    case 'get_capabilities': {
      const provider = msg.provider ?? 'claude';
      (async () => {
        try {
          const backend = getBackend(provider);
          const caps = await backend.gatherCapabilities?.(msg.cwd ?? process.cwd(), msg.sessionId, msg.customModels);
          send({ type: 'capabilities', requestId: msg.requestId ?? '', ...(caps ?? {}) });
        } catch (err: any) {
          send({ type: 'capabilities', requestId: msg.requestId ?? '', error: err?.message ?? String(err) });
        }
      })();
      break;
    }
    case 'store_credential': {
      const provider = msg.provider ?? 'claude';
      (async () => {
        try {
          const backend = getBackend(provider);
          if (!backend.storeCredential) throw new Error(`Provider ${provider} does not accept API keys`);
          await backend.storeCredential(msg.key ?? '');
          send({ type: 'credential_stored', requestId: msg.requestId ?? '', ok: true });
        } catch (err: any) {
          send({ type: 'credential_stored', requestId: msg.requestId ?? '', ok: false, error: err?.message ?? String(err) });
        }
      })();
      break;
    }
    case 'clear_credential': {
      const provider = msg.provider ?? 'claude';
      (async () => {
        try {
          const backend = getBackend(provider);
          if (!backend.clearCredential) throw new Error(`Provider ${provider} has no credential to clear`);
          await backend.clearCredential();
          send({ type: 'credential_cleared', requestId: msg.requestId ?? '', ok: true });
        } catch (err: any) {
          send({ type: 'credential_cleared', requestId: msg.requestId ?? '', ok: false, error: err?.message ?? String(err) });
        }
      })();
      break;
    }
    case 'clear_context': {
      if (msg.sessionId) {
        deleteContext(msg.sessionId);
        // Tell every provider that has cached state for this session to drop it,
        // so they don't try to resume from a now-deleted lastSdkSessionId on
        // the next turn. Sync per-backend call — they just clear in-memory refs.
        for (const b of backends.values()) b.resetSession?.(msg.sessionId);
      }
      break;
    }
    case 'slash_command': {
      const provider = msg.provider ?? 'claude';
      (async () => {
        try {
          const backend = getBackend(provider);
          if (!backend.handleSlashCommand) {
            send({ type: 'slash_result', requestId: msg.requestId ?? '', result: { type: 'pass-through' } });
            return;
          }
          const result = await backend.handleSlashCommand(msg.cmd ?? '', msg.args ?? '', send);
          // Provider's `/clear` only clears its own in-memory state. Mirror it
          // to disk here so the next process restart doesn't resurrect the
          // just-cleared session via `restoreContext`. Both the legacy
          // `context-cleared` SlashResult and the new `handled` path (where
          // provider emits slash_response itself) for `/clear` need this — we
          // gate on cmd name so the new path doesn't lose persistence cleanup.
          if (msg.sessionId && (result.type === 'context-cleared' || (result.type === 'handled' && msg.cmd === 'clear'))) {
            deleteContext(msg.sessionId);
          }
          send({ type: 'slash_result', requestId: msg.requestId ?? '', result });
        } catch (err: any) {
          send({ type: 'slash_result', requestId: msg.requestId ?? '', result: { type: 'error', message: err?.message ?? String(err) } });
        }
      })();
      break;
    }
  }
});

rl.on('close', () => {
  for (const b of backends.values()) b.dispose();
  process.exit(0);
});

cleanupOldContexts();
send({ type: 'ready' });
