export const FAKE_TEST_ENV = {
  CAPS_FAIL: 'SHELF_TEST_CAPS_FAIL',
  CAPS_DELAY: 'SHELF_TEST_CAPS_DELAY',
  LOGIN_SUCCESS: 'SHELF_TEST_LOGIN_SUCCESS',
  POST_LOGIN_CAPS_FAIL: 'SHELF_TEST_POST_LOGIN_CAPS_FAIL',
} as const;
